FGPH/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("recipes.urls"))
]

recipes/urls.py
from django.urls import path
from . import views

app_name = "recipes"
urlpatterns = [
    path("", views.index_blank, name="index_blank"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("signup", views.signup_view, name="signup"),

    path("<str:section>", views.index, name="index"),
    path("sections/<str:section>", views.section, name="section")


]

recipes/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser

class MyUserManager(BaseUserManager):
    def create_user(self, email, username, date_of_birth, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not email:
            raise ValueError("Users must have an email address")

        user = self.model(
            email=self.normalize_email(email),
            username=username,
            date_of_birth=date_of_birth,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, date_of_birth, password=None):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            email,
            username=username,
            password=password,
            date_of_birth=date_of_birth,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user

class MyUser(AbstractBaseUser):
    email = models.EmailField(
        verbose_name="email address",
        max_length=255,
        unique=True,
    )
    username = models.CharField(max_length=64)
    first_name = models.CharField(max_length=64, default="")
    last_name = models.CharField(max_length=64, default="")
    date_of_birth = models.DateField()
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = MyUserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["date_of_birth", "username"]

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

# Create your models here.
class Recipe(models.Model):
    REGIONS = {
        "RegionI" : "Ilocos Region",
        "RegionII" : "Cagayan Valley",
        "RegionIII" : "Central Luzon",
        "RegionIV‑A" : "CALABARZON",
        "MIMAROPA" : "MIMAROPA Region",
        "RegionV" : "Bicol Region",
        "CAR" : "Cordillera Administrative Region",
        "NCR" : "National Capital Region" 
    }

    name = models.CharField(max_length=171)
    description = models.CharField(max_length=750)
    region = models.CharField(max_length=64, choices=REGIONS)
    author = models.ForeignKey(MyUser, on_delete=models.CASCADE, related_name="recipes")
    ingredients = models.JSONField(blank=True)
    steps = models.JSONField(blank=True)

    def __str__(self):
        return f"{self.name}, description: {self.description}, region: {self.region}, author: {self.author.username}, ingredients: {self.ingredients}"

class Customer(models.Model):
    

    '''
    recipe = Recipe.objects.all()
    recipe = Recipe.objects.first()
    user = MyUser.objects.get(email="gavila_02@mtc.edu.ph")
    region = Recipe.REGIONS["RegionI"]
    recipe = Recipe(name="Pinakbet", description="Has vegetables.", region=region, author=user, ingredients="")
    '''

recipes/views.py
from django.contrib.auth import authenticate, login, logout
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.template.loader import get_template, render_to_string
from django.shortcuts import render
from django.urls import reverse
from .models import Recipe

# Create your views here.
sections = ["authentic", "signature", "content", "profile", "cookbooks", "settings"]


def index(request, section):
    global sections
    
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("recipes:login"))
    
    if section in sections:
        return render(request, "recipes/home.html", {
                "section": section,
                "name": request.user.username,
                "regions": Recipe.REGIONS.values()
        })
    else:
        return index_blank(request)

def index_blank(request):
    return index(request, "authentic")

def section(request, section):
    global sections
    print("from section function: " + section)
    print(type(section))

    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("recipes:login"))
    
    if section in sections:
        return render(request, f"recipes/sections/{section}.html", {
            "section": section,
            "name": request.user.username,
            "regions": Recipe.REGIONS.values()
        })
        print(type(content))

    else:
        raise Http404("Web Page does not exist.")

def login_view(request):
    if request.method == "POST":
        email = request.POST["email"]
        password = request.POST["password"]
        user = authenticate(request, email=email, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("recipes:index_blank"))
        else:
            return render(request, "recipes/login.html", {
                "message": "Invalid credentials."
            })
    return render(request, "recipes/login.html")

def logout_view(request):
    logout(request)
    return render(request, "recipes/login.html", {
        "message": "Successfully Logged Out"
    })

def signup_view(request):
    pass

FGPH/recipes/templates/recipes/AccountSettings copy.html
</DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <Title>FOOD GUIDE PH</Title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" 
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    
</head>

<body class="bg-black">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" 
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    
    <section class="text-white">
        <nav class="navbar bg-dark-subtle">
            <div class="container-fluid">
                <a href="Authentic Recipes.html"><img src="Logo.png" class="rounded float-center position-relative m-2" width="100px"> <label class="text-black">FOOD GUIDE PH</label></a> 
                    <ul class="nav nav-underline ms-4 text-black">
                        <li class="nav-item">
                            <a class="nav-link text-black" href="Authentic Recipes.html">Authentic Recipes</a>
                        </li>
    
                        <li class="nav-item">
                            <a class="nav-link text-black" href="Signature Recipes.html">Signature Recipes</a>
                        </li>
    
                        <li class="nav-item">
                            <a class="nav-link active text-black" aria-current="page" href="Profile.html">Profile</a>
                        </li>  
                            
                        <form class="d-flex" role="search">
                            <input class="form-control" type="search" placeholder="Search" aria-label="Search">
                            <button class="btn btn-outline-success" type="submit">Search</button>
                    </ul>
                </div>
            </nav>

        <div class="lead text-center">
            <img src="profile pic.png" class="rounded-center mt-2" width="100px">
                                
                <div class="my-3">
                    <label class="my-2">noobmaster69</label>  

                    <div class="container text-center">
                        <div class="row ">
                            <div class="col-md-3 container text-start">  
                                <label for="First Name"><h4>First Name</h4></label>
                                    <input type="text" class="form-control rounded-pill border border-5" placeholder="First Name" aria-label="First Name">                
                            </div>

                            <div class="col-3 container text-start"> 
                                <label for="Last Name"><h4>Last Name</h4></label>
                                    <input type="text" class="form-control rounded-pill border border-5" placeholder="Last Name" aria-label="Last Name">              
                            </div>

                            <div class="col-6 container text-start">
                            <label for="Username"><h4>Username</h4></label>               
                                <input type="text" class="form-control rounded-pill border border-5" placeholder="Username">
                            </div> 

                            <div class="col-6 container text-start">
                            <label for="Email"><h4>E-mail/Username</h4></label></ul>               
                                <input type="text" class="form-control rounded-pill border border-5" placeholder="Email">
                            </div>

                            <div class="col-6 container text-start">
                            <label for="password"><h4>Password</h4></label></ul>               
                                <input type="password" class="form-control rounded-pill border border-5" placeholder="Password">
                            </div>
                        </div>
                            
                    <div class="lead text-center mt-4">
                        <a href="Profile.html"><button  class="btn btn-outline-primary"><h3> Save Changes</h3></button></a>
                    </div>
                    </div>
                </div>
        </div>
    </section>
</body>
</html>

FGPH/recipes/templates/recipes/AccountSettings.html
</DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <Title>FOOD GUIDE PH</Title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" 
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    
</head>

<body class="bg-black">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" 
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    
    <section class="text-white">
        <nav class="navbar bg-dark-subtle">
            <div class="container-fluid">
                <a href="Authentic Recipes.html"><img src="Logo.png" class="rounded float-center position-relative m-2" width="100px"><label class="text-black">FOOD GUIDE PH</label></a> 
                    <ul class="nav nav-underline ms-4 text-black">
                        <li class="nav-item">
                            <a class="nav-link text-black" href="Authentic Recipes.html">Authentic Recipes</a>
                        </li>
    
                        <li class="nav-item">
                            <a class="nav-link text-black" href="Signature Recipes.html">Signature Recipes</a>
                        </li>
    
                        <li class="nav-item">
                            <a class="nav-link active text-black" aria-current="page" href="Profile.html">Profile</a>
                        </li>  
                            
                        <form class="d-flex" role="search">
                            <input class="form-control" type="search" placeholder="Search" aria-label="Search">
                            <button class="btn btn-outline-success" type="submit">Search</button>
                    </ul>
                </div>
            </nav>

        <div class="lead text-center">
            <img src="profile pic.png" class="rounded-center mt-2" width="100px">
                                
                <div class="my-3">
                    <label class="my-2">noobmaster69</label>  

                    <div class="container text-center">
                        <div class="row ">
                            <div class="col-md-3 container text-start">  
                                <label for="First Name"><h4>First Name</h4></label>
                                    <input type="text" class="form-control rounded-pill border border-5" placeholder="First Name" aria-label="First Name">                
                            </div>

                            <div class="col-3 container text-start"> 
                                <label for="Last Name"><h4>Last Name</h4></label>
                                    <input type="text" class="form-control rounded-pill border border-5" placeholder="Last Name" aria-label="Last Name">              
                            </div>

                            <div class="col-6 container text-start">
                            <label for="Username"><h4>Username</h4></label>               
                                <input type="text" class="form-control rounded-pill border border-5" placeholder="Username">
                            </div> 

                            <div class="col-6 container text-start">
                            <label for="Email"><h4>E-mail/Username</h4></label></ul>               
                                <input type="text" class="form-control rounded-pill border border-5" placeholder="Email">
                            </div>

                            <div class="col-6 container text-start">
                            <label for="password"><h4>Password</h4></label></ul>               
                                <input type="password" class="form-control rounded-pill border border-5" placeholder="Password">
                            </div>
                        </div>
                            
                    <div class="lead text-center mt-4">
                        <a href="Profile.html"><button  class="btn btn-outline-primary"><h3> Save Changes</h3></button></a>
                    </div>
                    </div>
                </div>
        </div>
    </section>
</body>
</html>

FGPH/recipes/templates/recipes/Authentic Recipes copy.html
</DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <Title>FOOD GUIDE PH</Title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" 
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    
    
</head>

<body class="bg-black">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" 
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    
    <section class="text-white">
        <nav class="navbar bg-dark-subtle">
            
            <div class="container-fluid">
            <a href="Authentic Recipes.html"><img src="Logo.png" class="rounded float-center position-relative m-2" width="100px"> <label class="text-black">FOOD GUIDE PH</label></a> 
                <ul class="nav nav-underline ms-4 text-black">
                    <li class="nav-item">
                        <a class="nav-link active text-black" aria-current="page" href="Authentic Recipes.html">Authentic Recipes</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link text-black" href="Signature Recipes.html">Signature Recipes</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link text-black" href="Profile.html">Profile</a>
                    </li>  
                        
                    <form class="d-flex" role="search">
                        <input class="form-control" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success" type="submit">Search</button>
                </ul>
            </div>
        </nav>
            <ul class="nav nav-underline ms-1">
                  <li class="nav-item"><a class="nav-link active text-white" aria-current="page" href="#">NCR</a></li>
                  <li class="nav-item"><a class="nav-link text-white" href="#">CAR</a></li>
                  <li class="nav-item"><a class="nav-link text-white" href="#">Region I</a></li>
                  <li class="nav-item"><a class="nav-link text-white" href="#">Region II</a></li>
                  <li class="nav-item"><a class="nav-link text-white" href="#">Region III</a></li>
                  <li class="nav-item"><a class="nav-link text-white" href="#">Region IV-A</a></li>
                  <li class="nav-item"><a class="nav-link text-white" href="#">Region IV-B</a></li>
                  <li class="nav-item"><a class="nav-link text-white" href="#">Region V</a></li>
                  <li class="nav-item"><a class="nav-link text-white" href="#">Region VI</a></li>
                  <li class="nav-item"><a class="nav-link text-white" href="#">Region VII</a></li>
                  <li class="nav-item"><a class="nav-link text-white" href="#">Region VIII</a></li>
                  <li class="nav-item"><a class="nav-link text-white" href="#">Region IX</a></li>
                  <li class="nav-item"><a class="nav-link text-white" href="#">Region X</a></li>
                  <li class="nav-item"><a class="nav-link text-white" href="#">Region XI</a></li>
                  <li class="nav-item"><a class="nav-link text-white" href="#">Region XII</a></li>
                  <li class="nav-item"><a class="nav-link text-white" href="#">Region XIII</a></li>
                  <li class="nav-item"><a class="nav-link text-white" href="#">BARMM</a></li>
            </ul>

            <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle lead text-center" type="button" data-bs-toggle="dropdown" aria-expanded="false">Filters</button>
                <ul class="dropdown-menu ms-2">
                  <li class="ms-2"><a class="dropdown-item" href="#"></a>Popular</li>
                  <li class="ms-2"><a class="dropdown-item" href="#"></a>Recommended</li>
                </ul>
              </div>

            <div class="lead text-center ">
                <label >Top Categories</label>
            </div>
    </section>

</body>
</html>

FGPH/recipes/templates/recipes/Cookbooks copy.html
</DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <Title>FOOD GUIDE PH</Title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" 
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    
</head>

<body class="bg-black">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" 
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    
    <section class="text-white">
        <nav class="navbar bg-dark-subtle">
            
            <div class="container-fluid">
                <a href="Authentic Recipes.html"><img src="Logo.png" class="rounded float-center position-relative m-2" width="100px"> <label class="text-black">FOOD GUIDE PH</label></a> 
                    <ul class="nav nav-underline ms-4 text-black">
                        <li class="nav-item">
                            <a class="nav-link text-black" href="Authentic Recipes.html">Authentic Recipes</a>
                        </li>
    
                        <li class="nav-item">
                            <a class="nav-link text-black" href="Signature Recipes.html">Signature Recipes</a>
                        </li>
    
                        <li class="nav-item">
                            <a class="nav-link active text-black" aria-current="page" href="Profile.html">Profile</a>
                        </li>  
                            
                        <form class="d-flex" role="search">
                            <input class="form-control" type="search" placeholder="Search" aria-label="Search">
                            <button class="btn btn-outline-success" type="submit">Search</button>
                    </ul>
                </div>
            </nav>
        <div class="lead text-center">
            <label><h1>Cookbooks</h1></label>
        </div>
        <div class="lead text-center">
            <label><h5>Lunch</h5></label>
        </div>
        <div class="lead text-center">
            <label><h5>Breakfast</h5></label>
        </div>
        <div class="lead text-center">
            <label><h5>Dinner</h5></label>
        </div>
</section>

</body>
</html>

FGPH/recipes/templates/recipes/Cookbooks.html
</DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <Title>FOOD GUIDE PH</Title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" 
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    
</head>

<body class="bg-black">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" 
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    
    <section class="text-white">
        <nav class="navbar bg-dark-subtle">
            
            <div class="container-fluid">
                <a href="Authentic Recipes.html"><img src="Logo.png" class="rounded float-center position-relative m-2" width="100px"><label class="text-black">FOOD GUIDE PH</label></a> 
                    <ul class="nav nav-underline ms-4 text-black">
                        <li class="nav-item">
                            <a class="nav-link text-black" href="Authentic Recipes.html">Authentic Recipes</a>
                        </li>
    
                        <li class="nav-item">
                            <a class="nav-link text-black" href="Signature Recipes.html">Signature Recipes</a>
                        </li>
    
                        <li class="nav-item">
                            <a class="nav-link active text-black" aria-current="page" href="Profile.html">Profile</a>
                        </li>  
                            
                        <form class="d-flex" role="search">
                            <input class="form-control" type="search" placeholder="Search" aria-label="Search">
                            <button class="btn btn-outline-success" type="submit">Search</button>
                    </ul>
                </div>
            </nav>
        <div class="lead text-center">
            <label><h1>Cookbooks</h1></label>
        </div>
        <div class="lead text-center">
            <label><h5>Lunch</h5></label>
        </div>
        <div class="lead text-center">
            <label><h5>Breakfast</h5></label>
        </div>
        <div class="lead text-center">
            <label><h5>Dinner</h5></label>
        </div>
</section>

</body>
</html>

FGPH/recipes/templates/recipes/Profile copy.html
</DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <Title>FOOD GUIDE PH</Title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" 
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    
</head>

<body class="bg-black">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" 
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    
    <section class="text-white">
        <nav class="navbar bg-dark-subtle">
            
            <div class="container-fluid">
                <a href="Authentic Recipes.html"><img src="Logo.png" class="rounded float-center position-relative m-2" width="100px"> <label class="text-black">FOOD GUIDE PH</label></a> 
                    <ul class="nav nav-underline ms-4 text-black">
                        <li class="nav-item">
                            <a class="nav-link text-black" href="Authentic Recipes.html">Authentic Recipes</a>
                        </li>
    
                        <li class="nav-item">
                            <a class="nav-link text-black" href="Signature Recipes.html">Signature Recipes</a>
                        </li>
    
                        <li class="nav-item">
                            <a class="nav-link active text-black" aria-current="page" href="Profile.html">Profile</a>
                        </li>  
                            
                        <form class="d-flex" role="search">
                            <input class="form-control" type="search" placeholder="Search" aria-label="Search">
                            <button class="btn btn-outline-success" type="submit">Search</button>
                    </ul>
                </div>
            </nav>

        <div class="lead text-center text-white">
            <img src="profile pic.png" class="rounded-center mt-2" width="100px">
                                
                <div class="my-3">
                    <label class="my-2">noobmaster69</label>  
                    <ul class="me-4 mt-3">
                    <a href="Cookbooks.html"><button class="cookbooks">Cookbooks</button></a>
                    </ul>
                    <ul class="me-4 mb-5 pb-4">
                    <a href="AccountSettings.html"><button class="setting">Account Setting</button></a>
                    </ul>

                    <div class="lead text-center ms-2 mt-4">
                        <a href="SignInPage.html"><button  class="btn btn-outline-primary"><h3> Log Out</h3></button></a>
                    </div>
                </div>                       
        </div>
    </section>
</body>
</html>

FGPH/recipes/templates/recipes/Profile.html
{% extends "recipes/layout.html" %}
{% load static %}

{% block body %}
<section class="text-white">
    <div class="lead text-center text-white">
        <img src="{% static 'images/avatar.png' %}" class="rounded-center mt-2" width="100px">
                            
            <div class="my-3">
                <label class="my-2">{{ name }}</label>  
                <ul class="me-4 mt-3">
                <a href="Cookbooks.html"><button class="cookbooks">Cookbooks</button></a>
                </ul>
                <ul class="me-4 mb-5 pb-4">
                <a href="AccountSettings.html"><button class="setting">Account Settings</button></a>
                </ul>

                <div class="lead text-center ms-2 mt-4">
                    <a class="btn btn-outline-primary " href="{% url 'recipes:logout' %}">Log Out</a>

                </div>
            </div>                       
    </div>
</section>
{% endblock %}

recipes/templates/recipes/login.html
{% extends 'recipes/loginLayout.html' %}
{% load static %}

{% block body %}
<section class="text-white">
    <header class="lead text-start  bg-dark-subtle">
        <img src="{% static 'images/logo.png' %}" 
            class="rounded float-center position-relative m-2" 
            width="100px">
    </header>
    {% if message == "Successfully Logged Out" %}
        <div class="alert alert-success alert-dismissible" role="alert">
            <div>{{ message }}</div>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% elif message %}
        <div class="alert alert-danger alert-dismissible" role="alert">
            <div>{{ message }}</div>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endif %}

    <div class="container fluid text-white">
        <div class="lead text-center">
            <div class="row">
                <form action="{% url 'recipes:login' %}" method="post">
                    {% csrf_token %}
                    <p><h1 class="bg.primary ms-3">Sign In</h1></p>
    
                    <div class="col-5 container text-start">
                        <label><h4>Email</h4></label></ul>               
                        <input 
                            type="email" 
                            class="form-control rounded-pill border border-5" 
                            name="email"
                            placeholder="Email" 
                            >
                
    
                        <label for="password"><h4>Password</h4></label></ul>               
                        <input 
                            type="password" 
                            class="form-control rounded-pill border border-5" 
                            name="password"
                            placeholder="Password"
                            >
                    </div>
    
                    <label for="SignUp" class="bg.primary ms-0">Don't have an account?</label>
                    <a href="{% url 'recipes:signup' %}">Sign Up</a>
    
                    <div class="bg.primary my-4 py-4">    
                        <div class="lead text-center">
                            <!--<a href="{% url 'recipes:login' %}"><button class="btn btn-outline-primary"><h3>Log In</h3></button></a>
                            -->
                            <input 
                                type="submit"
                                class="btn btn-outline-primary"
                                style="--bs-btn-font-size: 1rem;"
                                value="Login">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

recipes/templates/recipes/sections/profile.html
{% load static %}
<div class="pt-2 ps-2 text-white position-relative">
    <i class="bi bi-arrow-left"><use xlink:href="#arrow-left"></use></i>
    </div>
<div class="lead text-center text-white">
    <img src="{% static 'images/avatar.png' %}" class="rounded-center mt-2" width="100px">
                        
    <div class="my-3">
        <label class="my-2">{{ name }}</label>
        
        <div style="margin-bottom: 1rem;">
            <button data-section="cookbooks" class="navButton">Cookbooks</button>
        </div>

        <div>
            <button data-section="settings" class="navButton">Settings</button>
        </div>

        <div class="lead text-center mt-4">
            <a href="{% url 'recipes:logout' %}" class="btn btn-outline-primary" >Log Out</a>
        </div>
    </div>                       
</div>